#!/usr/bin/env python3
import os
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
README_PATH = ROOT / "README.md"
INDEX_XML = ROOT / "repo" / "index.xml"
METADATA_DIR = ROOT / "metadata"

HEADER = "<!-- This table is auto-generated. Do not edit -->"
FOOTER = "<!-- end apps table -->"


def parse_app(app_elem):
    app_id = app_elem.findtext("id")
    name = app_elem.findtext("name") or app_id
    summary = app_elem.findtext("summary") or ""
    source = app_elem.findtext("source") or ""
    marketversion = app_elem.findtext("marketversion")
    marketvercode = app_elem.findtext("marketvercode")
    version = marketversion
    versioncode = marketvercode

    if not version or not versioncode:
        package = app_elem.find("package")
        if package is not None:
            version = version or package.findtext("version")
            versioncode = versioncode or package.findtext("versioncode")

    if not version and not versioncode:
        package = app_elem.find("package[@versioncode]")
        if package is not None:
            version = version or package.findtext("version")
            versioncode = versioncode or package.get("versioncode")

    if not version:
        version = "?"
    if not versioncode:
        versioncode = "?"

    source_url = source.strip()
    if source_url.startswith("git+"):
        source_url = source_url[4:]

    icon_path = ROOT / "repo" / app_id / "en-US" / "icon.png"
    if not icon_path.exists():
        icon_path = ROOT / "repo" / f"{app_id}.png"
    if not icon_path.exists():
        icon_path = ROOT / "repo" / "icon.png"

    icon_rel = os.path.relpath(icon_path, ROOT).replace(os.sep, "/")
    github_url = source_url
    if github_url.endswith(".git"):
        github_url = github_url[:-4]
    if not github_url.startswith("http"):
        github_url = "#"

    return {
        "id": app_id,
        "name": name,
        "summary": summary.strip().replace("\n", " ").replace("  ", " "),
        "version": version,
        "versioncode": versioncode,
        "source_url": github_url,
        "icon": icon_rel,
    }


def build_table(apps):
    lines = ["| Icon | Name | Description | Version |", "| --- | --- | --- | --- |"]
    for app in sorted(apps, key=lambda x: x["name"].lower()):
        icon = f'<a href="{app["source_url"]}"><img src="{app["icon"]}" alt="{app["name"]} icon" width="36px" height="36px"></a>'
        title = f'[{app["name"]}]({app["source_url"]})' if app["source_url"] != "#" else app["name"]
        title = f'**{title}**' if app["source_url"] != "#" else f'**{app["name"]}**'
        lines.append(f"| {icon} | {title} | {app['summary']} | {app['version']} ({app['versioncode']}) |")
    return lines


def update_readme(table_lines):
    content = README_PATH.read_text(encoding="utf-8")
    start = content.find(HEADER)
    end = content.find(FOOTER, start)
    if start == -1 or end == -1:
        raise RuntimeError("Could not find autogenerated table markers in README.md")

    new_table = "\n".join([HEADER, *table_lines, FOOTER])
    before = content[:start].rstrip()
    after = content[end + len(FOOTER):].lstrip()
    new_content = f"{before}\n{new_table}\n\n{after}"
    if new_content != content:
        README_PATH.write_text(new_content, encoding="utf-8")
        return True
    return False


def validate_metadata(app_ids):
    missing = []
    extra = []
    for app_id in app_ids:
        if not (METADATA_DIR / f"{app_id}.yml").exists():
            missing.append(app_id)
    for metadata_file in METADATA_DIR.glob("*.yml"):
        app_id = metadata_file.stem
        if app_id not in app_ids:
            extra.append(app_id)
    return missing, extra


def main():
    if not INDEX_XML.exists():
        print(f"ERROR: repo/index.xml nicht gefunden: {INDEX_XML}")
        return 1

    tree = ET.parse(INDEX_XML)
    root = tree.getroot()
    apps = [parse_app(elem) for elem in root.findall("application")]
    table_lines = build_table(apps)
    changed = update_readme(table_lines)
    missing, extra = validate_metadata([app["id"] for app in apps])

    if changed:
        print("README.md aktualisiert.")
    else:
        print("README.md ist aktuell.")

    if missing:
        print("WARNUNG: Für diese Apps fehlt die Metadaten-Datei:")
        for app_id in missing:
            print(f"  - {app_id}")
    if extra:
        print("INFO: Diese Metadaten-Dateien sind im Repo, aber nicht im repo/index.xml:")
        for app_id in extra:
            print(f"  - {app_id}")

    if not changed and not missing and not extra:
        print("Keine Änderungen erforderlich.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
