sdk_path: /home/jamie/android-sdk
apksigner: /usr/bin/apksigner

gradle: /home/jamie/repos/gradlew-fdroid/gradlew-fdroid

ndk_paths:
  r28c: /home/jamie/android-sdk/ndk/28.0.13004108

repo_icon: icon.png
repo_name: Freetime Repository
repo_description: This is the Official F-Droid Repository from Freetime Maker for F-Droid. It includes Apps from Freetime Maker and others. It gets Updates from Freetime Maker directly and faster than the Official F-Droid Repository from F-Droid and includes Apps that aren't in the F-Droid Repository yet.
repo_url: https://fdroid.free-time.me/repo

archive_older: 3

keystore: keystore.p12
keystorepass: KKKKKK
keypass: KKKKKK
repo_keyalias: fdroid
keydname: CN=Freetime Maker, OU=F-Droid