sdk_path: /usr/local/lib/android/sdk
apksigner: /usr/local/lib/android/sdk/build-tools/37.0.0/apksigner

repo_icon: icon.png
repo_name: Freetime Repo
repo_description: The official F-Droid repository by Freetime Maker. Providing the latest versions of apps like GeoWeather and SuperSMP Companion. Updates are published here directly and are often available much faster than in the main F-Droid Repository.
repo_url: https://raw.githubusercontent.com/FreetimeMaker/fdroid/main/fdroid/repo

archive_older: 3

keystore: keystore.p12
keystorepass: KKKKKK
keypass: KKKKKK
repo_keyalias: fdroid
keydname: CN=Freetime Maker, OU=F-Droid
