name: Build F-Droid Repo & Deploy Jekyll to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  build_fdroid:
    name: "Build F-Droid Repo"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout Keystore Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEYSTORE_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: temp_secrets

      # ---------------------------------------------------------
      # Install dependencies
      # ---------------------------------------------------------

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget unzip imagemagick aapt yq apksigner zipalign

      - name: Install fdroidserver
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install fdroidserver androguard==4.1.1

      - name: Set up repo secrets
        run: |
          # Kopiere alle Dateien aus dem Root des Keystore-Repos in den lokalen fdroid-Ordner
          cp -r temp_secrets/. fdroid/
          rm -rf temp_secrets
          
          # Korrigiere Pfade in der config.yml für den GitHub Runner
          sed -i 's|apksigner: .*|apksigner: /usr/bin/apksigner|' fdroid/config.yml
          
          # Berechtigungen korrigieren (Sicherheitsanforderung von fdroid)
          chmod 0600 fdroid/config.yml
          [ -f fdroid/keystore.p12 ] && chmod 0600 fdroid/keystore.p12

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.0'

      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      # ---------------------------------------------------------
      # Build Jekyll site
      # ---------------------------------------------------------

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./fdroid/repo
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
