name: Generate F-Droid repo

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: "45 2 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime
          git restore-mtime

      - name: Install F-Droid server software
        run: |
          sudo apt install -y python3 python3-venv git
          git clone https://gitlab.com/fdroid/fdroidserver.git
          cd fdroidserver
          python3 -m venv venv
          source venv/bin/activate
          pip install .

      - name: Set up repo secrets
        run: |
          echo ./fdroid/keystore.p12
          echo ./fdroid/config.yml