name: Generate F-Droid repo keystore

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  
 
      - name: Set up JDK  
        uses: actions/setup-java@v4  
        with:  
          java-version: 17  
          distribution: 'temurin'  
 
      - name: Generate Keystore  
        run: |  
          keytool -genkeypair \  
            -alias fdroid \  
            -keyalg RSA \  
            -keysize 4096 \  
            -sigalg SHA256withRSA \ 
            -validity 10000 \  
            -keystore fdroid/keystore.p12 \ 
            -storetype PKCS12 \  
            -storepass KKKKKK \  
            -keypass KKKKKK \  
            -dname "CN=FreetimeMaker, OU=F-Droid"

      - name: Delete and Regenerate Keystore  
        run: |  
          rm keystore.p12 keytool -genkeypair \  
            -alias fdroid \  
            -keyalg RSA \  
            -keysize 4096 \  
            -sigalg SHA256withRSA \ 
            -validity 10000 \  
            -keystore fdroid/keystore.p12 \ 
            -storetype PKCS12 \  
            -storepass KKKKKK \  
            -keypass KKKKKK \  
            -dname "CN=FreetimeMaker, OU=F-Droid" -FreetimeMaker.language=en